
spring:
  datasource:
    url: jdbc:mysql://rm-uf6gyy2j9fh01u42x7o.mysql.rds.aliyuncs.com:3306/fun_funwork?useSSL=false&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: rds_dev
    password: RdsDev@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
##    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

mybatis:
  type-aliases-package: com.spring.data.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.spring.data.config.MyMapper
  not-empty: false
  identity: MYSQL

server:
  port: 80